import {
  BedDouble,
  Clock2,
  TriangleAlert,
  Users,
  TrendingUp,
  TrendingDown,
} from "lucide-react";

const dropdownItems = [
  { icon: "👤", label: "View Profile" },
  { icon: "⚙️", label: "Settings" },
  { icon: "🔔", label: "Notifications" },
  { icon: "🛡️", label: "Privacy" },
  { icon: "🚪", label: "Sign Out", danger: true },
];
const patientRows = [
  {
    id: "NV8831",
    name: "Liam Brown",
    initials: "LB",
    color: "#6366f1",
    status: "Admitted",
    waitTime: "45m",
    department: "ICU",
    priority: "Critical",
    age: 39,
    dob: "12/04/1984",
    reason: "Chest Pain",
    admitted: "11:30 AM",
    physician: "Dr. Chen",
    notes: "Labs pending, Vitals stable",
  },
  {
    id: "NV1042",
    name: "Sarah Chen",
    initials: "SC",
    color: "#ec4899",
    status: "Waiting",
    waitTime: "18m",
    department: "ED",
    priority: "High",
    age: 27,
    dob: "03/17/1997",
    reason: "Shortness of Breath",
    admitted: "12:05 PM",
    physician: "Dr. Patel",
    notes: "Oxygen levels low, monitoring",
  },
  {
    id: "NV3318",
    name: "Noah Davis",
    initials: "ND",
    color: "#f59e0b",
    status: "Critical",
    waitTime: "12m",
    department: "CCU",
    priority: "Immediate",
    age: 55,
    dob: "08/22/1969",
    reason: "Cardiac Arrest",
    admitted: "10:48 AM",
    physician: "Dr. Moore",
    notes: "Defibrillation administered",
  },
  {
    id: "NV7723",
    name: "Emma Wilson",
    initials: "EW",
    color: "#14b8a6",
    status: "Discharged",
    waitTime: "—",
    department: "Med-Surg",
    priority: "Routine",
    age: 34,
    dob: "05/30/1990",
    reason: "Post-op Recovery",
    admitted: "09:00 AM",
    physician: "Dr. Lewis",
    notes: "Cleared for discharge",
  },
  {
    id: "NV5591",
    name: "Mason Garcia",
    initials: "MG",
    color: "#8b5cf6",
    status: "Admitted",
    waitTime: "25m",
    department: "Ortho",
    priority: "High",
    age: 41,
    dob: "11/09/1983",
    reason: "Fracture — Left Femur",
    admitted: "01:15 PM",
    physician: "Dr. Kim",
    notes: "Surgery scheduled for 3 PM",
  },
  {
    id: "NV2204",
    name: "Ava Martinez",
    initials: "AM",
    color: "#06b6d4",
    status: "Waiting",
    waitTime: "—",
    department: "ED",
    priority: "Low",
    age: 22,
    dob: "02/14/2002",
    reason: "Mild Fever",
    admitted: "02:30 PM",
    physician: "Dr. Nguyen",
    notes: "Awaiting triage",
  },
  {
    id: "NV9910",
    name: "James Lee",
    initials: "JL",
    color: "#f43f5e",
    status: "Critical",
    waitTime: "8m",
    department: "ICU",
    priority: "Immediate",
    age: 63,
    dob: "07/04/1961",
    reason: "Stroke",
    admitted: "11:55 AM",
    physician: "Dr. Shah",
    notes: "CT scan in progress",
  },
  {
    id: "NV4477",
    name: "Olivia Scott",
    initials: "OS",
    color: "#22c55e",
    status: "Admitted",
    waitTime: "32m",
    department: "Neuro",
    priority: "High",
    age: 48,
    dob: "09/27/1976",
    reason: "Seizure",
    admitted: "12:40 PM",
    physician: "Dr. Patel",
    notes: "Anti-epileptics administered",
  },
];

const statusConfig = {
  Admitted: {
    bg: "#ccfbf1",
    color: "#0f766e",
    darkBg: "rgba(20,184,166,0.15)",
    darkColor: "#5eead4",
    dot: "#14b8a6",
  },
  Waiting: {
    bg: "#fef9c3",
    color: "#92400e",
    darkBg: "rgba(245,158,11,0.15)",
    darkColor: "#fcd34d",
    dot: "#f59e0b",
  },
  Critical: {
    bg: "#fee2e2",
    color: "#dc2626",
    darkBg: "rgba(239,68,68,0.15)",
    darkColor: "#fca5a5",
    dot: "#ef4444",
  },
  Discharged: {
    bg: "#f1f5f9",
    color: "#64748b",
    darkBg: "rgba(148,163,184,0.12)",
    darkColor: "#94a3b8",
    dot: "#94a3b8",
  },
};

const priorityConfig: { [key: string]: { light: string; dark: string } } = {
  Critical: { light: "#dc2626", dark: "#f87171" },
  Immediate: { light: "#b91c1c", dark: "#fca5a5" },
  High: { light: "#f97316", dark: "#fb923c" },
  Routine: { light: "#94a3b8", dark: "#64748b" },
  Low: { light: "#16a34a", dark: "#4ade80" },
};

const columns = [
  { key: "name", label: "Patient", width: "28%" },
  { key: "status", label: "Status", width: "18%" },
  { key: "waitTime", label: "Wait Time", width: "13%" },
  { key: "department", label: "Department", width: "18%" },
  { key: "priority", label: "Priority", width: "15%" },
];

const kpiCards = [
  {
    icon: Users,
    iconColor: "text-teal-500",
    iconBgLight: "bg-teal-50",
    iconBgDark: "bg-teal-900/30",
    glowColor: "rgba(20,184,166,0.18)",
    borderHoverLight: "hover:border-teal-300",
    borderHoverDark: "hover:border-teal-600",
    label: "Active Patients",
    value: "1,452",
    badge: "+5.8%",
    status: "Admitted",
    badgeIcon: TrendingUp,
  },
  {
    icon: BedDouble,
    iconColor: "text-blue-500",
    iconBgLight: "bg-blue-50",
    iconBgDark: "bg-blue-900/30",
    glowColor: "rgba(59,130,246,0.18)",
    borderHoverLight: "hover:border-blue-300",
    borderHoverDark: "hover:border-blue-600",
    label: "Bed Unoccupancy",
    value: "88%",
    badge: "-2.1%",
    status: "Discharged",
    badgeIcon: TrendingDown,
  },
  {
    icon: Clock2,
    iconColor: "text-cyan-500",
    iconBgLight: "bg-cyan-50",
    iconBgDark: "bg-cyan-900/30",
    glowColor: "rgba(6,182,212,0.18)",
    borderHoverLight: "hover:border-cyan-300",
    borderHoverDark: "hover:border-cyan-600",
    label: "Avg Wait Time",
    value: "28 min",
    badge: "-1.4m",
    status: "Waiting",
    badgeIcon: TrendingDown,
  },
  {
    icon: TriangleAlert,
    iconColor: "text-amber-500",
    iconBgLight: "bg-amber-50",
    iconBgDark: "bg-amber-900/30",
    glowColor: "rgba(245,158,11,0.18)",
    borderHoverLight: "hover:border-amber-300",
    borderHoverDark: "hover:border-amber-600",
    label: "Critical Alerts",
    value: "14",
    badge: "+2",
    status: "Critical",
    badgeIcon: TrendingUp,
  },
];

export {
  dropdownItems,
  patientRows,
  statusConfig,
  priorityConfig,
  columns,
  kpiCards,
};
